### ISSUE TITLE
cleaner handling of the dreaded no release return from helm 

### ISSUE THREAD

**Issue by compleatang** [gregdhill/compass#1]
```
rpc error: code = Unknown desc = "XXXXXX" has no deployed releases
```

**Comment by compleatang** [comment]
also, compass doesn't seem to be exiting non-0 when the above occurs.

**Comment by gregdhill** [comment]
fixed [here](https://github.com/gregdhill/compass/commit/436651c58b82c22ca834e9f25737e85c9f584092)
